// web/src/page/manager/Login.jsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { colors } from '@assets/colors';
import { useAuth } from '@context/AuthContext';
import authApi from '@api/manager/Auth';
import { Lock, Mail, LogIn, ArrowLeft, AlertCircle } from 'lucide-react';

const Login = () => {
  const navigate = useNavigate();
  const { login } = useAuth();
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [email, setEmail] = useState('admin@route.mg');
  const [password, setPassword] = useState('admin123');

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      console.log('Tentative de login avec:', email);
      const response = await authApi.login(email, password);
      console.log('Réponse API:', response);
      
      // L'API retourne { success, message, data: { token, user } }
      if (response.success && response.data) {
        console.log('Login réussi, token:', response.data.token);
        login(response.data.user, response.data.token);
        navigate('/manager/synchronisation');
      } else {
        console.error('Login échoué, réponse:', response);
        setError(response.message || 'Erreur de connexion');
      }
    } catch (err) {
      // Rester sur /manager/login en cas d'erreur
      console.error('Erreur login:', err);
      console.error('Response data:', err.response?.data);
      setError(err.response?.data?.message || 'Email ou mot de passe incorrect');
    } finally {
      setLoading(false);
    }
  };

  const styles = {
    page: {
      minHeight: '100vh',
      backgroundColor: colors.darker,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '24px',
      position: 'relative',
      overflow: 'hidden'
    },
    bgShape1: {
      position: 'absolute',
      top: '-10%',
      left: '-5%',
      width: '400px',
      height: '400px',
      borderRadius: '50%',
      background: `radial-gradient(circle, ${colors.primary}15 0%, transparent 70%)`,
      pointerEvents: 'none'
    },
    bgShape2: {
      position: 'absolute',
      bottom: '-15%',
      right: '-10%',
      width: '500px',
      height: '500px',
      borderRadius: '50%',
      background: `radial-gradient(circle, ${colors.secondary}12 0%, transparent 70%)`,
      pointerEvents: 'none'
    },
    bgLines: {
      position: 'absolute',
      top: '0',
      left: '0',
      right: '0',
      bottom: '0',
      backgroundImage: `
        linear-gradient(${colors.primary}05 1px, transparent 1px),
        linear-gradient(90deg, ${colors.primary}05 1px, transparent 1px)
      `,
      backgroundSize: '60px 60px',
      pointerEvents: 'none'
    },
    content: {
      position: 'relative',
      zIndex: 1,
      width: '100%',
      maxWidth: '400px'
    },
    header: {
      textAlign: 'center',
      marginBottom: '48px'
    },
    logoContainer: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '80px',
      height: '80px',
      backgroundColor: `${colors.primary}15`,
      borderRadius: '20px',
      marginBottom: '24px',
      border: `1px solid ${colors.primary}30`
    },
    logo: {
      width: '48px',
      height: '48px'
    },
    title: {
      fontSize: '32px',
      fontWeight: '700',
      color: 'white',
      margin: '0 0 8px 0',
      letterSpacing: '-0.5px'
    },
    subtitle: {
      fontSize: '15px',
      color: `${colors.primary}`,
      margin: 0,
      fontWeight: '500'
    },
    formCard: {
      backgroundColor: `${colors.dark}`,
      borderRadius: '24px',
      padding: '40px',
      border: `1px solid ${colors.primary}20`
    },
    formTitle: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '12px',
      marginBottom: '32px'
    },
    formTitleIcon: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '44px',
      height: '44px',
      backgroundColor: `${colors.primary}20`,
      borderRadius: '12px'
    },
    formTitleText: {
      fontSize: '20px',
      fontWeight: '600',
      color: 'white',
      margin: 0
    },
    form: {
      display: 'flex',
      flexDirection: 'column',
      gap: '24px'
    },
    inputGroup: {
      display: 'flex',
      flexDirection: 'column',
      gap: '8px'
    },
    label: {
      fontSize: '13px',
      fontWeight: '600',
      color: `rgba(255,255,255,0.7)`,
      textTransform: 'uppercase',
      letterSpacing: '0.5px'
    },
    inputWrapper: {
      position: 'relative'
    },
    inputIcon: {
      position: 'absolute',
      left: '16px',
      top: '50%',
      transform: 'translateY(-50%)',
      color: colors.primary,
      display: 'flex',
      pointerEvents: 'none'
    },
    input: {
      width: '100%',
      padding: '16px 16px 16px 52px',
      fontSize: '15px',
      fontFamily: 'inherit',
      color: 'white',
      backgroundColor: `${colors.darker}`,
      border: `2px solid ${colors.primary}30`,
      borderRadius: '12px',
      outline: 'none',
      transition: 'border-color 0.2s, box-shadow 0.2s',
      boxSizing: 'border-box'
    },
    errorBox: {
      display: 'flex',
      alignItems: 'center',
      gap: '10px',
      padding: '14px 16px',
      fontSize: '14px',
      color: '#F87171',
      backgroundColor: 'rgba(239, 68, 68, 0.1)',
      border: '1px solid rgba(239, 68, 68, 0.3)',
      borderRadius: '12px'
    },
    submitBtn: {
      width: '100%',
      padding: '16px 24px',
      fontSize: '16px',
      fontWeight: '600',
      fontFamily: 'inherit',
      color: colors.darker,
      backgroundColor: colors.primary,
      border: 'none',
      borderRadius: '12px',
      cursor: loading ? 'not-allowed' : 'pointer',
      opacity: loading ? 0.7 : 1,
      transition: 'all 0.2s',
      marginTop: '8px'
    },
    divider: {
      height: '1px',
      backgroundColor: `${colors.primary}20`,
      margin: '24px 0'
    },
    backBtn: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '8px',
      width: '100%',
      padding: '12px',
      fontSize: '14px',
      fontWeight: '500',
      fontFamily: 'inherit',
      color: `rgba(255,255,255,0.6)`,
      backgroundColor: 'transparent',
      border: `1px solid ${colors.primary}20`,
      borderRadius: '10px',
      cursor: 'pointer',
      transition: 'all 0.2s'
    }
  };

  return (
    <div style={styles.page}>
      <div style={styles.bgShape1} />
      <div style={styles.bgShape2} />
      <div style={styles.bgLines} />

      <div style={styles.content}>
        <header style={styles.header}>
          <div style={styles.logoContainer}>
            <img src="/logo.svg" alt="Lalan-tsara" style={styles.logo} />
          </div>
          <h1 style={styles.title}>Lalan-tsara</h1>
          <p style={styles.subtitle}>Espace Administration</p>
        </header>

        <div style={styles.formCard}>
          <div style={styles.formTitle}>
            <div style={styles.formTitleIcon}>
              <LogIn size={22} color={colors.primary} />
            </div>
            <h2 style={styles.formTitleText}>Connexion</h2>
          </div>

          <form onSubmit={handleSubmit} style={styles.form}>
            <div style={styles.inputGroup}>
              <label style={styles.label}>Email</label>
              <div style={styles.inputWrapper}>
                <div style={styles.inputIcon}>
                  <Mail size={18} />
                </div>
                <input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="votre@email.com"
                  required
                  style={styles.input}
                  onFocus={(e) => {
                    e.target.style.borderColor = colors.primary;
                    e.target.style.boxShadow = `0 0 0 3px ${colors.primary}20`;
                  }}
                  onBlur={(e) => {
                    e.target.style.borderColor = `${colors.primary}30`;
                    e.target.style.boxShadow = 'none';
                  }}
                />
              </div>
            </div>

            <div style={styles.inputGroup}>
              <label style={styles.label}>Mot de passe</label>
              <div style={styles.inputWrapper}>
                <div style={styles.inputIcon}>
                  <Lock size={18} />
                </div>
                <input
                  type="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="••••••••"
                  required
                  style={styles.input}
                  onFocus={(e) => {
                    e.target.style.borderColor = colors.primary;
                    e.target.style.boxShadow = `0 0 0 3px ${colors.primary}20`;
                  }}
                  onBlur={(e) => {
                    e.target.style.borderColor = `${colors.primary}30`;
                    e.target.style.boxShadow = 'none';
                  }}
                />
              </div>
            </div>

            {error && (
              <div style={styles.errorBox}>
                <AlertCircle size={18} />
                <span>{error}</span>
              </div>
            )}

            <button
              type="submit"
              disabled={loading}
              style={styles.submitBtn}
              onMouseEnter={(e) => {
                if (!loading) {
                  e.target.style.transform = 'translateY(-2px)';
                  e.target.style.boxShadow = `0 8px 20px ${colors.primary}40`;
                }
              }}
              onMouseLeave={(e) => {
                e.target.style.transform = 'translateY(0)';
                e.target.style.boxShadow = 'none';
              }}
            >
              {loading ? 'Connexion en cours...' : 'Se connecter'}
            </button>
          </form>

          <div style={styles.divider} />

          <button
            onClick={() => navigate('/')}
            style={styles.backBtn}
            onMouseEnter={(e) => {
              e.target.style.borderColor = colors.primary;
              e.target.style.color = 'white';
            }}
            onMouseLeave={(e) => {
              e.target.style.borderColor = `${colors.primary}20`;
              e.target.style.color = 'rgba(255,255,255,0.6)';
            }}
          >
            <ArrowLeft size={16} />
            Retour à l'accueil
          </button>
        </div>
      </div>
    </div>
  );
};

export default Login;

// mobile/src/views/Login.vue
<template>
  <ion-page>
    <ion-content :fullscreen="true" class="login-page">
      <!-- Background decoratif -->
      <div class="bg-decoration">
        <div class="bg-shape bg-shape-1"></div>
        <div class="bg-shape bg-shape-2"></div>
        <div class="bg-lines"></div>
      </div>

      <div class="login-container">
        <!-- Header avec logo -->
        <div class="login-header">
          <div class="logo-container">
            <i class="fas fa-road"></i>
          </div>
          <h1 class="app-title">Lalan-Tsara</h1>
          <p class="app-subtitle">Signalement routier</p>
        </div>

        <!-- Card de connexion -->
        <div class="login-card">
          <div class="card-header">
            <div class="card-icon">
              <i class="fas fa-sign-in-alt"></i>
            </div>
            <h2 class="card-title">Connexion</h2>
          </div>

          <form @submit.prevent="handleLogin" class="login-form">
            <!-- Email -->
            <div class="form-group">
              <label class="form-label">Email</label>
              <div class="input-wrapper">
                <i class="fas fa-envelope input-icon"></i>
                <input
                  v-model="formData.email"
                  type="email"
                  class="form-input"
                  placeholder="votre@email.com"
                  required
                />
              </div>
            </div>

            <!-- Password -->
            <div class="form-group">
              <label class="form-label">Mot de passe</label>
              <div class="input-wrapper">
                <i class="fas fa-lock input-icon"></i>
                <input
                  v-model="formData.password"
                  :type="showPassword ? 'text' : 'password'"
                  class="form-input"
                  placeholder="Votre mot de passe"
                  required
                />
                <button type="button" class="toggle-password" @click="showPassword = !showPassword">
                  <i :class="showPassword ? 'fas fa-eye-slash' : 'fas fa-eye'"></i>
                </button>
              </div>
            </div>

            <!-- Error Message -->
            <div v-if="error" class="error-box">
              <i class="fas fa-exclamation-circle"></i>
              <span>{{ error }}</span>
            </div>

            <!-- Submit Button -->
            <button type="submit" class="btn-submit" :disabled="loading">
              <ion-spinner v-if="loading" name="crescent"></ion-spinner>
              <template v-else>
                <i class="fas fa-arrow-right"></i>
                <span>Se connecter</span>
              </template>
            </button>
          </form>

          <!-- Divider -->
          <div class="divider">
            <span>ou</span>
          </div>

          <!-- Link to Register -->
          <div class="register-section">
            <p class="register-text">Pas encore de compte ?</p>
            <RouterLink :to="{ name: 'register' }" class="btn-register">
              <i class="fas fa-user-plus"></i>
              <span>Créer un compte</span>
            </RouterLink>
          </div>
        </div>

        <!-- Footer -->
        <p class="footer-text">
          <i class="fas fa-shield-alt"></i>
          Connexion sécurisée
        </p>
      </div>
    </ion-content>
  </ion-page>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useRouter, RouterLink } from 'vue-router';
import { IonPage, IonContent, IonSpinner, toastController, alertController } from '@ionic/vue';
import { login } from '@/services/firebase/authService';
import { isAccountBlocked, incrementLoginAttempts, resetLoginAttempts } from '@/services/userService';
import { getMaxLoginAttempts } from '@/config/auth';

const router = useRouter();
const loading = ref(false);
const error = ref('');
const showPassword = ref(false);

const formData = ref({
  email: '',
  password: ''
});

const handleLogin = async () => {
  error.value = '';
  loading.value = true;

  try {
    if (!formData.value.email || !formData.value.password) {
      throw new Error('Veuillez remplir tous les champs');
    }

    const blocked = await isAccountBlocked(formData.value.email);
    if (blocked) {
      const alert = await alertController.create({
        header: 'Compte bloqué',
        message: 'Votre compte a été bloqué suite à trop de tentatives de connexion échouées. Veuillez contacter un administrateur.',
        buttons: ['OK']
      });
      await alert.present();
      loading.value = false;
      return;
    }

    await login(formData.value.email, formData.value.password);
    await resetLoginAttempts(formData.value.email);
    
    const toast = await toastController.create({
      message: 'Connexion réussie !',
      duration: 1500,
      position: 'bottom',
      color: 'success'
    });
    await toast.present();

    router.push({ name: 'home' });
  } catch (err: any) {
    const result = await incrementLoginAttempts(formData.value.email);
    
    if (result.blocked) {
      error.value = 'Compte bloqué ! Trop de tentatives échouées.';
    } else if (result.attempts > 0) {
      const remaining = getMaxLoginAttempts() - result.attempts;
      error.value = `${err.message || 'Erreur de connexion'} (${remaining} tentative(s) restante(s))`;
    } else {
      error.value = err.message || 'Erreur lors de la connexion';
    }
    
    const toast = await toastController.create({
      message: error.value,
      duration: 3000,
      position: 'bottom',
      color: 'danger'
    });
    await toast.present();
  } finally {
    loading.value = false;
  }
};
</script>

<style scoped>
.login-page {
  --background: #243B4A;
}

.bg-decoration {
  position: absolute;
  inset: 0;
  overflow: hidden;
  pointer-events: none;
}

.bg-shape {
  position: absolute;
  border-radius: 50%;
}

.bg-shape-1 {
  top: -10%;
  left: -15%;
  width: 300px;
  height: 300px;
  background: radial-gradient(circle, rgba(135, 188, 222, 0.15) 0%, transparent 70%);
}

.bg-shape-2 {
  bottom: -15%;
  right: -10%;
  width: 350px;
  height: 350px;
  background: radial-gradient(circle, rgba(128, 94, 115, 0.12) 0%, transparent 70%);
}

.bg-lines {
  position: absolute;
  inset: 0;
  background-image: 
    linear-gradient(rgba(135, 188, 222, 0.03) 1px, transparent 1px),
    linear-gradient(90deg, rgba(135, 188, 222, 0.03) 1px, transparent 1px);
  background-size: 50px 50px;
}

.login-container {
  position: relative;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 100%;
  padding: 24px;
  z-index: 1;
}

.login-header {
  text-align: center;
  margin-bottom: 32px;
}

.logo-container {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 72px;
  height: 72px;
  background: rgba(135, 188, 222, 0.12);
  border: 2px solid rgba(135, 188, 222, 0.2);
  border-radius: 20px;
  margin-bottom: 16px;
}

.logo-container i {
  font-size: 32px;
  color: #87BCDE;
}

.app-title {
  font-size: 28px;
  font-weight: 700;
  color: white;
  margin: 0 0 4px 0;
  letter-spacing: -0.5px;
}

.app-subtitle {
  font-size: 14px;
  color: #87BCDE;
  margin: 0;
  font-weight: 500;
}

.login-card {
  width: 100%;
  max-width: 400px;
  background: #2D4654;
  border-radius: 24px;
  padding: 32px;
  border: 1px solid rgba(135, 188, 222, 0.15);
}

.card-header {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 12px;
  margin-bottom: 28px;
}

.card-icon {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 44px;
  height: 44px;
  background: rgba(135, 188, 222, 0.15);
  border-radius: 12px;
}

.card-icon i {
  font-size: 18px;
  color: #87BCDE;
}

.card-title {
  font-size: 20px;
  font-weight: 600;
  color: white;
  margin: 0;
}

.login-form {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.form-label {
  font-size: 13px;
  font-weight: 600;
  color: rgba(255, 255, 255, 0.7);
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.input-wrapper {
  position: relative;
}

.input-icon {
  position: absolute;
  left: 16px;
  top: 50%;
  transform: translateY(-50%);
  color: #87BCDE;
  font-size: 16px;
  pointer-events: none;
}

.form-input {
  width: 100%;
  padding: 16px 48px 16px 48px;
  font-size: 15px;
  font-family: inherit;
  color: white;
  background: #243B4A;
  border: 2px solid rgba(135, 188, 222, 0.2);
  border-radius: 12px;
  outline: none;
  transition: border-color 0.2s;
}

.form-input:focus {
  border-color: #87BCDE;
}

.form-input::placeholder {
  color: rgba(255, 255, 255, 0.4);
}

.toggle-password {
  position: absolute;
  right: 16px;
  top: 50%;
  transform: translateY(-50%);
  background: none;
  border: none;
  color: rgba(255, 255, 255, 0.5);
  cursor: pointer;
  padding: 4px;
}

.toggle-password:hover {
  color: #87BCDE;
}

.error-box {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 14px 16px;
  font-size: 14px;
  color: #F87171;
  background: rgba(239, 68, 68, 0.1);
  border: 1px solid rgba(239, 68, 68, 0.3);
  border-radius: 12px;
}

.error-box i {
  font-size: 16px;
}

.btn-submit {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
  width: 100%;
  padding: 16px 24px;
  font-size: 16px;
  font-weight: 600;
  font-family: inherit;
  color: #243B4A;
  background: #87BCDE;
  border: none;
  border-radius: 12px;
  cursor: pointer;
  transition: all 0.2s;
}

.btn-submit:hover:not(:disabled) {
  background: #6fa8cc;
}

.btn-submit:disabled {
  opacity: 0.7;
  cursor: not-allowed;
}

.divider {
  display: flex;
  align-items: center;
  gap: 16px;
  margin: 24px 0;
}

.divider::before,
.divider::after {
  content: '';
  flex: 1;
  height: 1px;
  background: rgba(135, 188, 222, 0.2);
}

.divider span {
  font-size: 13px;
  color: rgba(255, 255, 255, 0.5);
  text-transform: uppercase;
}

.register-section {
  text-align: center;
}

.register-text {
  font-size: 14px;
  color: rgba(255, 255, 255, 0.6);
  margin: 0 0 12px 0;
}

.btn-register {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 12px 24px;
  font-size: 14px;
  font-weight: 600;
  color: #87BCDE;
  background: transparent;
  border: 2px solid rgba(135, 188, 222, 0.3);
  border-radius: 12px;
  text-decoration: none;
  transition: all 0.2s;
}

.btn-register:hover {
  background: rgba(135, 188, 222, 0.1);
  border-color: #87BCDE;
}

.footer-text {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  margin-top: 24px;
  font-size: 13px;
  color: rgba(255, 255, 255, 0.4);
}

.footer-text i {
  color: #10B981;
}
</style>
